name: glados-vm
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - binary
  - bytestring
  - containers

executables:
  glados-vm:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -Wall
      - -Wextra
      - -threaded
