# This file defines the GLaDOS VM as a standalone project.
name: glados-vm
version: 0.1.0.0

# Dependencies required for the VM and bytecode parser.
dependencies:
  - base >= 4.7 && < 5
  - binary
  - bytestring
  - containers

# Executable definition
executables:
  glados-vm:
    main: Main.hs
    # The source files are in the current directory ('.') relative to this file.
    source-dirs: .
    ghc-options:
      - -Wall
      - -Wextra
      - -threaded
