name: glados-decompiler
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - binary
  - bytestring

executables:
  glados-decompiler:
    main: Main.hs
    source-dirs: .
    ghc-options:
      - -Wall
      - -Wextra
      - -threaded
