name:                glados-compiler
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- binary     
- mtl       
- directory 
# Fichier: compiler/package.yaml

# Le nom du projet global
name:                glados-compiler
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- binary
- mtl
- directory

library:
  source-dirs:
  - .
  - ../Parsing
  exposed-modules:
  - Main
  - Compiler
  - BytecodeConvertor
  - Parser.Data
  - Parser.Body
  - Parser.Tools
  - Parser.Constructor
  - Parser.Define
  - Parser.Parse
  - Parsing

executables:
  glados-compiler:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados-compiler


tests:
  glados-compiler-test:
    main:                Test.hs
    source-dirs:         ../test
    ghc-options:
    - -threaded
    - -fhpc
    dependencies:
    - glados-compiler
    - tasty
    - tasty-hunit
    - tasty-ant-xml