name: glados-compiler
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - binary
  - bytestring
  - containers
  - mtl
  - directory

executables:
  glados-compiler:
    main: Main.hs
    source-dirs:
      - .
      - ../Parser
      - ../Parsing
    ghc-options:
      - -Wall
      - -Wextra
      - -threaded
