name: Haskell CI

env:
  MIRROR_URL: git@github.com:EpitechPGE3-2025/G-FUN-500-LIL-5-1-glados-1.git

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  set_current_url:
    runs-on: ubuntu-latest
    outputs:
      current_url: ${{ steps.set_current_url.outputs.current_url }}
    steps:
      - name: Set CURRENT_URL
        id: set_current_url
        run: |
          echo "$MIRROR_URL"
          MIRROR_URL="$MIRROR_URL"
          CURRENT_URL=$(echo -e "$MIRROR_URL" | sed 's/.*://; s/\.git.*//')
          echo "current_url=$CURRENT_URL" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          stack-version: 'latest'

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-stack
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml') }}-${{ hashFiles('**/package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        run: stack build

  push_to_mirror:
    needs:
      - set_current_url
    if: ${{ !contains(needs.set_current_url.outputs.current_url, github.repository) || !contains(github.repository, needs.set_current_url.outputs.current_url) }} && ${{ github.event_name }} == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}